phoing/chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/home/', views.chat_home, name='chat_home'),
    path('pending/', views.chat_add_pendings, name='chat_add_pendings'),
    path('member/', views.chat_add_members, name='chat_add_members'),
    path('reject/', views.chat_add_rejected, name='chat_add_rejected'),
    path('<str:room_name>/', views.chat_room, name='room'),
   
]

phoing/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('user.urls')),
    path('', include('myApp.urls')),
    path('place/', include('place.urls')),
    path('chat/', include('chat.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

phoing/place/urls.py
from django.urls import path
from . import views

app_name = 'place'

urlpatterns = [
    #####################profile#######################
    path('', view=views.place_list, name='place_list'),
    path('map/', view=views.place_map, name='place_map'),
    path('create/', view=views.place_create, name='place_create'),
    path('detail/<int:pk>/',
         view=views.place_detail, name='place_detail'),
    path('<int:pk>/delete/',
         view=views.place_delete, name='place_delete'),
    path('<int:pk>/update/',
         view=views.place_update, name='place_update'),

    path('select/', view=views.place_select,
         name='place_select'),  # TODO : 나중에 삭제할 것


    # path('<int:pk>/comment_create/',
    #      view=views.place_comment_create, name='place_comment_create'),
    # path('<int:pk>/comment_delete/',
    #      view=views.place_comment_delete, name='place_comment_delete'),
    # path('save/', views.place_save, name='place_save'),

]

phoing/place/models.py
from django.db import models
from user.models import User
from myApp.utils import uuid_name_upload_to

# Create your models here.


class Location(models.Model):

    # location
    address = models.TextField()  # 도로명 주소
    lat = models.FloatField(blank=True)
    lon = models.FloatField(blank=True)

    def __str__(self):
        return self.address

phoing/place/forms.py
from .models import Location
from myApp.models import Place
from django import forms


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = ('address', 'lat', 'lon',)
        # exclude = ('start_date_time', 'end_date_time',)
        widgets = {
            'address': forms.TextInput(
                attrs={'class': 'form-control location location-address',
                       'id': 'location-address',
                       'style': 'width:100%; margin:0 auto;',
                       'placeholder': ''}
            ),
            'lat': forms.TextInput(
                attrs={'class': 'form-control location location-lat',
                       'id': 'location-lat',
                       'style': 'width:30%;'}
            ),
            'lon': forms.TextInput(
                attrs={'class': 'form-control location location-lon',
                       'id': 'location-lon',
                       'style': 'width:30%;'}
            ),
        }
        labels = {
            'address': '도로명 주소',
            'lat': 'latitude',
            'lon': 'longitude',
        }
        required = {
            # 'address':True,
            # 'lat':True,
            # 'lon':True,
        }


class PlaceForm(forms.ModelForm):

    class Meta:
        model = Place
        fields = ('thumbnail', 'title', 'desc', 'pay', 'tag_str')
        # exclude = ('start_date_time', 'end_date_time',)
        widgets = {
            # 'thumbnail': forms.ImageField(
            #     attrs={
            #         'class': 'form-control place place-thumbnail',
            #         'id': 'place-thumbnail',
            #     }
            # ),
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control place place-title',
                    'id': 'place-title',
                    'placeholder': ''
                }
            ),
            'desc': forms.Textarea(
                attrs={'class': 'form-control place place-desc',
                       'id': 'place-desc',
                       }
            ),
            # 'pay': forms.IntegerField(
            #     attrs={
            #         'class': 'form-control place place-pay',
            #         'id': 'place-pay',
            #     }
            # ),
            'tag_str': forms.TextInput(
                attrs={
                    'class': 'form-control place place-tag-str',
                    'id': 'place-tag-str',
                }
            ),
        }
        labels = {
            'thumbnail': 'Thumbnail',
            'title': 'Title',
            'desc': 'Description',
            'pay': 'Payment',
            'tag_str': 'Hashtag',
        }

        required = {
            'thumbnail': True,
            'title': True,
            'desc': True,
            'pay': True,
        }

phoing/place/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import LocationForm, PlaceForm
from django.contrib.auth.decorators import login_required
from myApp.models import Place, Tag
from django.contrib import messages
import json

# category filtering
from django.db.models import Count, Q

# infinite loading
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required
def place_create(request):

    if request.method == 'POST':
        place_form = PlaceForm(request.POST, request.FILES)
        location_form = LocationForm(request.POST)

        if place_form.is_valid() and location_form.is_valid():
            place = place_form.save(commit=False)
            location = location_form.save(commit=False)
            location.save()
            place.user = request.user
            place.location = location
            place.save()

            tags = Tag.add_tags(place.tag_str)
            for tag in tags:
                place.tags.add(tag)

            place.image = request.FILES.get('image')
            return redirect('place:place_detail', place.pk)

    else:
        place_form = PlaceForm()
        location_form = LocationForm()

    
    ctx = {
        'location_form': location_form,
        'place_form': place_form, 
    }

    return render(request, 'place/place_create.html', context=ctx)


def place_detail(request, pk):

    place = get_object_or_404(Place, pk=pk)
    request_user = request.user
    ctx = {
        'place' : place,
    }

    return render(request, 'place/place_detail.html', context=ctx)

@login_required
def place_update(request, pk):

    place = get_object_or_404(Place, pk=pk)
    
    if request.method == 'POST':
        place_form = PlaceForm(request.POST, request.FILES, instance=place)
        location_form = LocationForm(request.POST, instance=place.location)
        if place_form.is_valid() and location_form.is_valid():
            place = place_form.save(commit=False)
            location = location_form.save(commit=False)
            location.save()
            place.location = location
            place.image = request.FILES.get('image')

            place.tags.clear()
            tags = Tag.add_tags(place.tag_str)
            for tag in tags:
                place.tags.add(tag)

            place.save()
            return redirect('place:place_detail', place.pk)

    else:
        place_form = PlaceForm(instance=place)
        location_form = LocationForm(instance=place.location)

        ctx = {
        'place_form' : place_form,
        'location_form' : location_form,
        }
        
        return render(request, 'place/place_update.html', context=ctx)
            

    
def place_list(request):

    places = Place.objects.all()

    sort = request.GET.get('sort', 'recent')
    search = request.GET.get('search', '')

    # SORT
    if sort == 'pay':
        places = places.order_by('-pay', '-created_at')
    elif sort == 'recent':
        places = places.order_by('-created_at')

    if search:
        places = places.filter(
            Q(title__icontains=search) |  # 제목검색
            Q(desc__icontains=search) |  # 내용검색
            Q(user__username__icontains=search)  # 질문 글쓴이검색
        ).distinct()


    # infinite scroll
    places_per_page = 3
    page = request.GET.get('page', 1)
    paginator = Paginator(places, places_per_page)
    try:
        places = paginator.page(page)
    except PageNotAnInteger:
        places = paginator.page(1)
    except EmptyPage:
        places = paginator.page(paginator.num_pages)

    ctx = {
        'places': places,
        'sort': sort,
        'search': search,
    }

    return render(request, 'place/place_list.html', context=ctx)


@login_required
def place_delete(request, pk):

    place = get_object_or_404(Place, pk=pk)

    if request.method == 'POST':
        place.location.delete()
        place.delete()
        messages.success(request, '삭제되었습니다.')
        return redirect('place:place_list')
    
    else:
        ctx = {'place': place}
        return render(request, 'place/place_delete.html', context=ctx)



def place_map(request):

    places = Place.objects.all()

    ctx = {
        'places_json' : json.dumps([places.to_json() for place in places])
    }

    return render(request, 'place/place_map.html', context=ctx)



def place_select(request):

    form = LocationForm()

    ctx = {
        'form': form,
    }
    return render(request, 'place/place_select.html', context=ctx)

phoing/place/templates/place/place_delete.html
{% extends 'myApp/layout.html' %}

{% load static %}
{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/place_delete.css' %}">
{% endblock stylesheet %}

{% block content %}
<div class="container">
    <div class="contact_delete">
        <h1>Contact delete</h1><br>
        <form action="{% url 'place:place_delete' place.pk %}" method="POST">
            {% csrf_token %}
            <p>정말로 삭제하시겠습니까?</p>
            <input class="delete_btn" type="submit" value="삭제" />
        </form>
    </div>
</div>
{% endblock content%}

phoing/place/templates/place/place_detail.html
{% extends 'myApp/layout.html' %}

{% load static %}
{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/place_detail.css' %}">
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/moonspam/NanumSquare@1.0/nanumsquare.css">

{% endblock stylesheet %}

{% block content %}
<!-- 카테고리 왼쪽에 -->

<div>
    <!-- SHOW PROFILE 버튼 -->
    <p>
        <!--user img--> {{place.user}}</p>
    <p>{{ place.user.category }}</p>
    <p>{{ place.title }}</p>
    <div>
        <img src="{{ place.thumbnail.url }}" alt="">
    </div>
    <!-- DESC -->
    <a href="{{ place.file_attach.url }}">시안 첨부파일</a>
    <p>{{ place.pay }}</p>
    <!-- 촬영날짜/마감여부 -->
    <p>{{ place.start_date }}</p>
    <p>{{ place.end_date }}</p>
    <p>{{ place.location }}</p>

    <!-- 댓글,저장수 ajax -->

    <!--Comment-->
    <div class="comments-{{ place.id }} comments">
        {% for comment in place.place_comments.all %}
        <div class="comment comment-{{ comment.id }}">
            <span>{{ place.id }}</span>
            <span>{{ comment.id }}</span>
            <span>{{ comment.content }}</span>
            <input class="comment-btn" onclick="onClickDeleteComment({{ comment.id }})" type="submit" value="삭제">
        </div>
        {% endfor %}
    </div>
    <div class="createComment createComment-{{place.id}}">
        <input class="comment__value" type="text" placeholder="댓글 달기...">
        <input class="comment__btn" onclick="onClickNewComment({{ place.id }})" type="submit" value="게시">
    </div>

    <!-- 이게뭐져?? -->
    <p>request.user: {{ request.user.username }}</p>
    <p>place.user: {{ place.user.username }}</p>
    {% if request.user.pk == place.user.pk %}
    <div class="profile_button">
        <a class="edit_btn" href="{% url 'place:place_update' place.pk %}">Contact 수정</a>
        <a class="delete_btn" href="{% url 'place:place_delete' place.pk %}">Contact 삭제</a>
    </div>
    {% endif %}


    <div class="save">
        {% if request.user in place.save_users.all %}
        <i class="fas fa-bookmark" type="submit" onclick="onClickSave({{ place.id }})" name="type" value="save"></i>
        {% else %}
        <i class="far fa-bookmark" type="submit" onclick="onClickSave({{ place.id }})" name="type" value="save"></i>
        {% endif %}
        <span class="save__content">{{ place.save_users.count }}</span>
    </div>

</div>
{% endblock content%}
{% block script %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script type='text/javascript'>
    //Save
    const onClickSave = async (place_id) => {
        try {
            // const url = '/place/';
            // const {
            //     data
            // } = await axios.post(url, {
            //     place_id,
            // })
            // modify(data.place_id, data.is_saved)

            const options = {
                url: '/place/save/',
                method: 'POST',
                data: {
                    place_id: place_id,
                }
            }
            const response = await axios(options)
            const responseOK = response && response.status === 200 && response.statusText === 'OK'
            if (responseOK) {
                const data = response.data
                //modify에서는 이미 뒤집힌 is_saved 값이 들어감!
                modify(data.place_id, data.is_saved)
            }
        } catch (error) {
            console.log(error)
        }
    }

    const modify = (place_id, is_saved) => {
        const save = document.querySelector(`.save-${place_id} i`);
        const save_content = document.querySelector(`.save-${place_id} .save__content`)
        const num = save_content.innerText; // [ {{ place.save_users.count }} ]
        console.log(num)
        if (is_saved === true) {

            save.className = "fas fa-bookmark";

            const count = Number(num) + 1;
            save_content.innerHTML = count
        } else {
            save.className = "far fa-bookmark";

            const count = Number(num) - 1;
            save_content.innerHTML = count
        }

    }


    const modifyNewComment = (place_id, comment_id, value) => {
        const CommentContainer = document.querySelector(`.comments-${place_id}`);
        console.log(CommentContainer)

        const tempContainer = document.createElement("div");
        tempContainer.className = `comment comment-${comment_id}`;


        tempContainer.textContent = value;

        const deleteBtn = document.createElement("input");
        deleteBtn.className = "comment-btn";
        deleteBtn.setAttribute("type", "submit");
        deleteBtn.setAttribute("value", "삭제");
        deleteBtn.setAttribute("onclick", `onClickDeleteComment(${comment_id})`)

        tempContainer.appendChild(deleteBtn);
        CommentContainer.appendChild(tempContainer);
    }

    const onClickNewComment = async (id) => {
        const url = `/place/${id}/comment_create/`;
        const value = document.querySelector(`.createComment-${id} .comment__value`);
        const value_text = value.value
        const {
            data
        } = await axios.post(url, {
            id,
            value: value_text
        })

        modifyNewComment(id, data.comment_id, data.value);
    }

    const modifyDeleteComment = (comment_id) => {

        const targetCommentContainer = document.querySelector(`.comment-${comment_id}`);
        targetCommentContainer.remove();
    }

    const onClickDeleteComment = async (comment_id) => {
        const url = `/place/${comment_id}/comment_delete/`;

        const {
            data
        } = await axios.post(url, {
            comment_id
        })
        modifyDeleteComment(data.comment_id);
    }
</script>
{% endblock script %}

phoing/place/templates/place/place_list.html
{% extends 'myApp/layout.html' %}
{% load static %}


{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/place_list.css' %}">
<style>
    /* modal */
    #my_modal {
    display: none;
    width: 80%;
    padding: 20px 60px;
    background-color: #fefefe;
    border: 1px solid #888;
    border-radius: 3px;
    }

    #my_modal .modal_close_btn {
    position: absolute;
    top: 10px;
    right: 10px;
    }

    #map {
    height: 400px;
    overflow: scroll;
    }


</style>
{% endblock stylesheet %}


{% block content %}


<div class="place_list">
    <!--category-->
    <div class="placelist_left">
        
    </div>

    <div class="placelist_right">
        <div class="bar">

            <!--search-->
            <div class="input-group">
                <input type="text" class="form-control search" value="{{ search|default_if_none:"" }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary btn_search" type="button" id="">찾기</button>
                </div>
            </div>

            <!--sort-->
            <div class="sort">
                <select name="" id="" class="form-control sort ">
                    <option value="recent" {% if sort == 'recent' %}selected{% endif %}>
                        최신순
                    </option>
                    <!-- <option value="save" {% if sort == 'save' %}selected{% endif %}>
                        저장순
                    </option> -->
                    <option value="pay" {% if sort == 'pay' %}selected{% endif %}>
                        가격순
                    </option>
                </select>
            </div>


            <!--contact_create-->
            <div class="place_create">
                {% if request.user.is_authenticated %}
                <a class="update_btn" href="{% url 'place:place_create' %}"><i class="far fa-plus-square"></i></a>
                {% endif %}
            </div>

            
            <!-- 모달...어렵네... 지도가 어려운건가 -->
            <!-- <div class="contact_map"> 
                <div id="my_modal">
                    <div id="map"></div>
                    <br />
                    <a class="modal_close_btn">닫기</a>
                </div>

                <button id="popup_open_btn">위치 확인하기</button>
            </div> -->
            <button id="popup_open_btn">
                <a href="{% url 'place:place_map' %}">위치 확인하기</a>
            </button>
        </div>


        <!--contact_list-->
        <div class="content">
            <!---->
            <div class="infinite-container">
                {% for place in places %}

                <div class="infinite-item">
                    <div class="item_top place-{{place.pk}}">
                        <div>
                            <!-- user_img -->
                            User : {{ place.user }}
                        </div>
                        <a href="{% url 'place:place_detail' place.pk %}">
                            <div>{{ place.title }}</div>
                        </a>
                        <div class="thumbnail_desc">
                            <img src="{{ place.thumbnail.url }}" alt="">
                            <div class="desc">
                                <!-- desc ... -->
                            </div>
                        </div>
                        <div class="pay_date">
                            {% if place.pay == 0 %}
                            Pay : 상호 무페이
                            {% else %}
                            Pay : {{ place.pay }}원
                            {% endif %}
                            <!-- 촬영날짜나 isclosed check되었으면 마감알림 -->
                        </div>
                    </div>

                    <div class="item_bottom">
                        <div class="comment">
                            <i class="far fa-comment-dots"></i>
                            <span class="comment__content">{{ place.place_comments.count }}</span>
                        </div>

                        <div class="save save-{{place.id}}">
                            {% if request.user in place.save_users.all %}
                            <i class="fas fa-bookmark" type="submit" onclick="onClickSave({{ place.id }})" name="type"
                                value="save"></i>
                            {% else %}
                            <i class="far fa-bookmark" type="submit" onclick="onClickSave({{ place.id }})" name="type"
                                value="save"></i>
                            {% endif %}
                            <span class="save__content">{{ place.save_users.count }}</span>
                        </div>

                    </div>


                    <!--
                    <div class="caption">
                        <div class="caption-content">
                            <p>더 알아보기<i style="font-size: 1em;" class="fas fa-search"></i> </p>
                        </div>
                    </div>
                    -->
                </div>

                {% endfor %}
            </div>


            <!-- 무한로딩 보류 -->
            {% if places.has_next %}
            <a class="infinite-more-link" href="?page={{ places.next_page_number }}">
                <div class="loading" style="display: none;">Loading...</div>
            </a>
            {% endif %}

            <!--filter form-->
            <div style="height: 0;">
                <form id="searchForm" method="get" action="{% url 'place:place_list' %}">
                    <!--category-->
                    <input type="hidden" id="category" name="category" value="{{ category }}">
                    <!--sort-->
                    <input type="hidden" id="search" name="search" value="{{ search|default_if_none:'' }}">
                    <!--search-->
                    <input type="hidden" id="sort" name="sort" value="{{ sort }}">
                </form>
            </div>
        </div>


       


        

    </div>

    <div>
        {% endblock content %}



        <!--js-->
        {% block script %}
        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.1.1.min.js"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
        <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
        <script src="{% static 'js/infinite.min.js' %}"></script>

        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
        <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=b6bc437b6340a6a287508c2a0e89a88b&libraries=services"></script>
        <script src="{% static 'js/place_list_map.js' %}" ></script>
        

        <script>
            var infinite = new Waypoint.Infinite({
                element: $('.infinite-container')[0],
                onBeforePageLoad: function () {
                    $('.loading').show();
                },
                onAfterPageLoad: function ($items) {
                    $('.loading').hide();
                }
            });

            //Save
            const onClickSave = async (place_id) => {
                try {
                    // const url = '/contact/';
                    // const {
                    //     data
                    // } = await axios.post(url, {
                    //     place_id,
                    // })
                    // modify(data.place_id, data.is_saved)

                    const options = {
                        url: '/place/save/',
                        method: 'POST',
                        data: {
                            place_id: place_id,
                        }
                    }
                    const response = await axios(options)
                    const responseOK = response && response.status === 200 && response.statusText === 'OK'
                    if (responseOK) {
                        const data = response.data
                        //modify에서는 이미 뒤집힌 is_saved 값이 들어감!
                        modify(data.place_id, data.is_saved)
                    }
                } catch (error) {
                    console.log(error)
                }
            }

            const modify = (place_id, is_saved) => {
                const save = document.querySelector(`.save-${place_id} i`);
                const save_content = document.querySelector(`.save-${place_id} .save__content`)
                const num = save_content.innerText; // [ {{ contact.save_users.count }} ]
                console.log(num)
                if (is_saved === true) {

                    save.className = "fas fa-bookmark";

                    const count = Number(num) + 1;
                    save_content.innerHTML = count
                } else {
                    save.className = "far fa-bookmark";

                    const count = Number(num) - 1;
                    save_content.innerHTML = count
                }

            }
            //category
            const onClickLink = (category) => {
                const categoryIdInput = document.querySelector('#category')
                categoryIdInput.value = category
                const searchForm = document.querySelector('#searchForm')
                searchForm.submit()
            }

            //search
            const searchButton = document.querySelector('.btn_search')
            searchButton.addEventListener('click', () => {
                const searchClassInput = document.querySelector('.search')
                const searchIdInput = document.querySelector('#search')
                const searchForm = document.querySelector('#searchForm')
                searchIdInput.value = searchClassInput.value
                searchForm.submit()
            })


            //sort
            const sortClassInput = document.querySelector('.sort')
            sortClassInput.addEventListener('input', (e) => {
                const sortIdInput = document.querySelector('#sort')
                const searchForm = document.querySelector('#searchForm')
                sortIdInput.value = e.target.value
                searchForm.submit()
            })


            function modal(id) {
                var zIndex = 9999;
                var modal = document.getElementById(id);

                // 모달 div 뒤에 희끄무레한 레이어
                var bg = document.createElement('div');
                bg.setStyle({
                    position: 'fixed',
                    zIndex: zIndex,
                    left: '0px',
                    top: '0px',
                    width: '100%',
                    height: '100%',
                    overflow: 'auto',
                    // 레이어 색갈은 여기서 바꾸면 됨
                    backgroundColor: 'rgba(0,0,0,0.4)'
                });
                document.body.append(bg);

                // 닫기 버튼 처리, 시꺼먼 레이어와 모달 div 지우기
                modal.querySelector('.modal_close_btn').addEventListener('click', function() {
                    bg.remove();
                    modal.style.display = 'none';
                });

                modal.setStyle({
                    position: 'fixed',
                    display: 'block',
                    boxShadow: '0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)',

                    // 시꺼먼 레이어 보다 한칸 위에 보이기
                    zIndex: zIndex + 1,

                    // div center 정렬
                    top: '50%',
                    left: '50%',
                    transform: 'translate(-50%, -50%)',
                    msTransform: 'translate(-50%, -50%)',
                    webkitTransform: 'translate(-50%, -50%)'
                });
            }

            // Element 에 style 한번에 오브젝트로 설정하는 함수 추가
            Element.prototype.setStyle = function(styles) {
                for (var k in styles) this.style[k] = styles[k];
                return this;
            };

            document.getElementById('popup_open_btn').addEventListener('click', function() {
                // 모달창 띄우기
                modal('my_modal');
            });

           


        </script>
        {% endblock script %}

        

phoing/place/templates/place/place_map.html
{% extends 'myApp/layout.html' %}
{% load static %}

{% block stylesheet %}

{% endblock stylesheet %}


{% block content %}

<div id="map" style="width:100%;height:350px;"></div>

{% endblock content%}


{% block script %}

<script>
    let places = {{ places_json|safe }};
</script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=b6bc437b6340a6a287508c2a0e89a88b&libraries=services"></script>
<script type="text/javascript" src="{% static 'js/contact/contact_map.js' %}"></script>

{% endblock script%}

phoing/place/templates/place/place_select.html
{% extends 'myApp/layout.html' %}
{% load static %}


{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/place_select.css' %}">
{% endblock stylesheet %}

{% block content %}

<p>마커를 드래그해 위치를 설정하세요!</p>
<button id="button">검색창 열기/닫기</button>

<div class="map_wrap">
    <div id="map" style="width:100%;height:100%;position:relative;overflow:hidden;"></div>

    <div id="menu_wrap" class="bg_white">
        <div class="option">
            <div>
                <form onsubmit="searchPlaces(); return false;">
                    키워드 : <input type="text" value="" id="keyword" size="15" placeholder="검색어를 입력하세요"> 
                    <button type="submit">검색하기</button> 
                </form>
            </div>
        </div>
        <hr>
        <ul id="placesList"></ul>
        <div id="pagination"></div>
    </div>
</div>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit">
</form>
  
{% endblock content %}



{% block script %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=b6bc437b6340a6a287508c2a0e89a88b&libraries=services"></script>
<script type="text/javascript" src="{% static 'js/place_select.js' %}"></script>

{% endblock script%}