phoing/chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/home/', views.chat_home, name='chat_home'),
    path('pending/', views.chat_add_pendings, name='chat_add_pendings'),
    path('member/', views.chat_add_members, name='chat_add_members'),
    path('reject/', views.chat_add_rejected, name='chat_add_rejected'),
    path('<str:room_name>/', views.chat_room, name='room'),
   
]

phoing/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('user.urls')),
    path('', include('myApp.urls')),
    path('place/', include('place.urls')),
    path('chat/', include('chat.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

phoing/myApp/urls.py
from django.urls import path
from . import views

app_name = 'myApp'

urlpatterns = [
     path('login/general_login', view=views.general_login, name='general_login'),
    #####################profile#######################
    path('', view=views.main_list, name='main_list'),
    path('profile/<int:pk>/', view=views.profile_detail, name='profile_detail'),
    path('profile/<int:pk>/posts/',
         view=views.profile_detail_posts, name='profile_detail_posts'),
     path('profile/<int:pk>/saves/',
         view=views.profile_detail_saves, name='profile_detail_saves'),
    path('profile/<int:pk>/delete/',
         view=views.profile_delete, name='profile_delete'),
    path('profile/<int:pk>/update/',
         view=views.profile_update, name='profile_update'),
    path('profile/<int:pk>/profile_update_password/',
         view=views.profile_update_password, name='profile_update_password'),
    path('profile/create/', view=views.profile_create, name='profile_create'),
    path('profile/post/create/', view=views.post_create, name='post_create'),

    #####################contact#######################
    path('contact/', view=views.contact_list, name='contact_list'),
    #path('contact/<string:category>', view=views.contact_category, name='contact_category'),
    path('contact/map/', view=views.contact_map, name='contact_map'),
    path('contact/detail/<int:pk>/',
         view=views.contact_detail, name='contact_detail'),
    path('contact/<int:pk>/comment_create/',
         view=views.contact_comment_create, name='contact_comment_create'),
    path('contact/<int:pk>/comment_delete/',
         view=views.contact_comment_delete, name='contact_comment_delete'),
    path('contact/<int:pk>/delete/',
         view=views.contact_delete, name='contact_delete'),
    path('contact/<int:pk>/update/',
         view=views.contact_update, name='contact_update'),
    path('contact/create/', view=views.contact_create, name='contact_create'),
    path('contact/save/', views.contact_save, name='contact_save'),

    #####################portfolio#######################
    path('portfolio/',
         view=views.portfolio_list, name='portfolio_list'),
    path('portfolio/<int:pk>/', view=views.portfolio_detail,
         name='portfolio_detail'),
    path('portfolio/<int:pk>/delete/',
         view=views.portfolio_delete, name='portfolio_delete'),
    path('portfolio/<int:pk>/update/',
         view=views.portfolio_update, name='portfolio_update'),
    path('portfolio/create/', view=views.portfolio_create, name='portfolio_create'),
    path('portfolio/like/', view=views.portfolio_like,
         name='portfolio_like'),
    path('portfolio/save/', view=views.portfolio_save,
         name='portfolio_save'),

    #####################reference#######################
    #1. from phoging(local) #
    path('local/', view=views.local_list, name='local_list'),
    path('local/<slug:tag>/', view=views.local_detail, name='local_detail'),


    #2. from reference(pinterest) #
    path('reference/', view=views.reference_list, name='reference_list'),
    path('reference/detail/<int:pk>/',
         view=views.reference_detail, name='reference_detail'),

    #####################collaborations#######################

    #1. with brand #
    path('with_brand/', view=views.with_brand_list, name='with_brand_list'),
    #path('with_brand/<string:category>', view=views.with_brand_category, name='with_brand_category'),
    path('with_brand/map/', view=views.with_brand_map, name='with_brand_map'),
    path('with_brand/detail/<int:pk>/',
         view=views.with_brand_detail, name='with_brand_detail'),
    path('with_brand/<int:pk>/comment_create/',
         view=views.with_brand_comment_create, name='with_brand_comment_create'),
    path('with_brand/<int:pk>/comment_delete/',
         view=views.with_brand_comment_delete, name='with_brand_comment_delete'),
    path('with_brand/<int:pk>/delete/',
         view=views.with_brand_delete, name='with_brand_delete'),
    path('with_brand/<int:pk>/update/',
         view=views.with_brand_update, name='with_brand_update'),
    path('with_brand/create/', view=views.with_brand_create,
         name='with_brand_create'),
    path('with_brand/save/', view=views.with_brand_save, name='with_brand_save'),

    #2. with artist #
    path('with_artist/', view=views.with_artist_list, name='with_artist_list'),
    #path('with_artist/<str2aing:category>', view=views.with_artist_category, name='with_artist_category'),
    path('with_artist/map/', view=views.with_artist_map,
         name='with_artist_map'),
    path('with_artist/detail/<int:pk>/',
         view=views.with_artist_detail, name='with_artist_detail'),
    path('with_artist/<int:pk>/comment_create/',
         view=views.with_artist_comment_create, name='with_artist_comment_create'),
    path('with_artist/<int:pk>/comment_delete/',
         view=views.with_artist_comment_delete, name='with_artist_comment_delete'),
    path('with_artist/<int:pk>/delete/',
         view=views.with_artist_delete, name='with_artist_delete'),
    path('with_artist/<int:pk>/update/',
         view=views.with_artist_update, name='with_artist_update'),
    path('with_artist/create/', view=views.with_artist_create,
         name='with_artist_create'),
    path('with_artist/save/', view=views.with_artist_save,
         name='with_artist_save'),

]

phoing/myApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http.response import HttpResponse
from .forms import *
from user.models import *
from .models import *
import random
from django.http import JsonResponse

# for SAVE, LIKE
import json
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.contrib.auth import login as auth_login
from .utils import *
from place.forms import LocationForm

# category filteringx
from django.db.models import Count, Q

# infinite loading
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# for multiple images
from django.forms import modelformset_factory

# for change password
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
# web chat
from chat.models import *

def main_list(request):
    ctx = {}
    return render(request, 'myApp/main/main_list.html', context=ctx)

###################### profile section ######################



###################### portfolio section ######################

# @api_view(['GET'])
def portfolio_list(request):
    portfolios = Portfolio.objects.all().order_by("?")
    request_user = request.user

    # category 분류 # order_by("?"): random 으로 선택
    category = request.GET.get('category', 'all')

    if category != 'all':
        if category == User.CATEGORY_PHOTOGRAPHER:
            portfolios = portfolios.filter(Q(user__category=User.CATEGORY_PHOTOGRAPHER)
                                           ).distinct().order_by("?")
        elif category == User.CATEGORY_MODEL:
            portfolios = portfolios.filter(Q(user__category=User.CATEGORY_MODEL)
                                           ).distinct().order_by("?")
        elif category == User.CATEGORY_HM:
            portfolios = portfolios.filter(Q(user__category=User.CATEGORY_HM)
                                           ).distinct().order_by("?")
        elif category == User.CATEGORY_STYLIST:
            portfolios = portfolios.filter(Q(user__category=User.CATEGORY_STYLIST)
                                           ).distinct().order_by("?")
        elif category == User.CATEGORY_OTHERS:
            portfolios = portfolios.filter(Q(user__category=User.CATEGORY_OTHERS)
                                           ).distinct().order_by("?")

    # SORT 최신순, 조회순, 좋아요순, 저장순
    sort = request.GET.get('sort', 'recent')

    if sort == 'recent':
        portfolios = portfolios.order_by('-updated_at')
    elif sort == 'view':
        portfolios = portfolios.annotate(num_save=Count(
            'view_count')).order_by('-num_save', '-updated_at')
    elif sort == 'like':
        portfolios = portfolios.annotate(num_save=Count(
            'like_users')).order_by('-num_save', '-updated_at')
    elif sort == 'save':
        portfolios = portfolios.annotate(num_save=Count(
            'save_users')).order_by('-num_save', '-updated_at')

    # infinite scroll
    portfolios_per_page = 6
    page = request.GET.get('page', 1)
    paginator = Paginator(portfolios, portfolios_per_page)
    try:
        portfolios = paginator.page(page)
    except PageNotAnInteger:
        portfolios = paginator.page(1)
    except EmptyPage:
        portfolios = paginator.page(paginator.num_pages)

    context = {'portfolios': portfolios, 'request_user': request.user, 'sort': sort,
               'category': category, }
    return render(request, 'myApp/portfolio/portfolio_list.html', context=context)


def portfolio_detail(request, pk):
    portfolio = Portfolio.objects.get(pk=pk)
    images = portfolio.portfolio_images.all()
    num_of_imgs = images.count

    tags = portfolio.tags.all()

    portfolio_owner = portfolio.user  # 게시글 작성자
    request_user = request.user  # 로그인한 유저

    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    print(ip)

    # 조회수

    try: 
        view_counts=ViewCount.objects.get(ip=ip, post=portfolio)
    except Exception as e:
        print(e)
        view_counts=ViewCount(ip=ip, post=portfolio)
        Portfolio.objects.filter(pk=pk).update(view_count=portfolio.view_count+1)
        view_counts.save()
    else:
        if not view_counts.date == timezone.localtime().date():
            Portfolio.objects.filter(pk=pk).update(view_count=portfolio.view_count+1)
            view_counts.date=timezone.localtime()
            view_counts.save()
        else:
            print(str()+'has already hit his post.\n\n')



    ctx = {'portfolio': portfolio,
           'images': images,
           'tags': tags,
           'portfolio_owner': portfolio_owner,
           'request_user': request_user,
           'num_of_imgs': num_of_imgs, }
    return render(request, 'myApp/portfolio/portfolio_detail.html', context=ctx)


@login_required
def portfolio_delete(request, pk):
    portfolio = Portfolio.objects.get(pk=pk)
    owner = portfolio.user
    if request.method == 'POST':
        portfolio.delete()
        messages.success(request, "삭제되었습니다.")
        return redirect('myApp:profile_detail_posts', owner.id)
    else:
        ctx = {'portfolio': portfolio}
        return render(request, 'myApp/portfolio/portfolio_delete.html', context=ctx)


@login_required
def portfolio_update(request, pk):
    portfolio = get_object_or_404(Portfolio, pk=pk)
    if request.method == 'POST':
        form = PortfolioForm(request.POST, request.FILES, instance=portfolio)
        if form.is_valid():
            portfolio = form.save(commit=False)
            portfolio.user = request.user
            portfolio.save()
            portfolio.image = request.FILES.get('image')

            portfolio.tags.all().delete()

            # save tag
            tags = Tag.add_tags(portfolio.tag_str)
            for tag in tags:
                portfolio.tags.add(tag)

            return redirect('myApp:portfolio_detail', portfolio.id)
    else:
        form = PortfolioForm(instance=portfolio)
        ctx = {'form': form,}
        return render(request, 'myApp/portfolio/portfolio_update.html', ctx)


@login_required
def portfolio_create(request):
    ImageFormSet = modelformset_factory(Images, form=ImageForm, extra=10)
    # 'extra' : number of photos
    if request.method == 'POST':
        form = PortfolioForm(request.POST, request.FILES,)
        formset = ImageFormSet(request.POST, request.FILES,
                               queryset=Images.objects.none())

        if form.is_valid() and formset.is_valid():
            portfolio = form.save(commit=False)
            portfolio.user = request.user
            portfolio.save()
            portfolio.image = request.FILES.get('image')
            for form in formset.cleaned_data:
                if form:
                    image = form['image']
                    
                    photo = Images(portfolio=portfolio, image=image)
                    photo.save()
            messages.success(request, "posted!")

            # # prev_tag
            # prev_tags = Tag.objects.all()
            # save tag
            tags_portfolio = Tag.add_tags(portfolio.tag_str)
            for tag in tags_portfolio:
                portfolio.tags.add(tag)

            # # tag compare
            # # tags_portfolio의 tag가 tag_all에 있는지 확인하고
            # # 이미 있으면 do nothing
            # # 없으면 tag 게시물 create
            # local_create(request, prev_tags)

            return redirect('myApp:portfolio_detail', portfolio.pk)
        else:
            print(form.errors, formset.errors)

    else:
        form = PortfolioForm()
        formset = ImageFormSet(queryset=Images.objects.none())
        ctx = {'form': form, 'formset': formset}

    return render(request, 'myApp/portfolio/portfolio_create.html', ctx)


@csrf_exempt
def portfolio_save(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        portfolio_id = data["portfolio_id"]
        portfolio = get_object_or_404(Portfolio, pk=portfolio_id)
        request_user = request.user
        is_saved = request_user in portfolio.save_users.all()
        if is_saved:
            portfolio.save_users.remove(
                get_object_or_404(User, pk=request_user.pk))
        else:
            portfolio.save_users.add(
                get_object_or_404(User, pk=request_user.pk))
        is_saved = not is_saved
        portfolio.save()
        return JsonResponse({'portfolio_id': portfolio_id, 'is_saved': is_saved})


@csrf_exempt
def portfolio_like(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        portfolio_id = data["portfolio_id"]
        portfolio = get_object_or_404(Portfolio, pk=portfolio_id)
        request_user = request.user
        is_liked = request_user in portfolio.like_users.all()
        if is_liked:
            portfolio.like_users.remove(
                get_object_or_404(User, pk=request_user.pk))
        else:
            portfolio.like_users.add(
                get_object_or_404(User, pk=request_user.pk))
        is_liked = not is_liked
        portfolio.save()
        return JsonResponse({'portfolio_id': portfolio_id, 'is_liked': is_liked})


# TODO view_count 수정
@csrf_exempt
def portfolio_view(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        portfolio_id = data["portfolio_id"]
        portfolio = get_object_or_404(Portfolio, pk=portfolio_id)
        request_user = request.user
        is_viewed = request_user in portfolio.view_count.all()
        portfolio.save_users.add(get_object_or_404(User, pk=request_user.pk))
        is_saved = not is_saved
        portfolio.save()
        return JsonResponse({'portfolio_id': portfolio_id, 'is_saved': is_saved})

phoing/myApp/templates/myApp/reference_local/local_list.html
{% extends 'myApp/layout.html' %}
{% load static %}
{% block stylesheet %}
<style>
    .top_nav {
        border-bottom: rgb(201, 201, 201) solid 1px;
        display: flex;
        padding: 20px;
        justify-content: center;
    }

    .top_nav div {
        padding-left: 12px;
        padding-right: 12px;
    }

    .top_nav .pinterest {
        margin-right: 5%;
    }

    /*page*/

    .top_nav .local a {
        font-weight: bold;
    }

    .top_nav .local {
        border-left: rgb(185, 185, 185) 1px solid;
        border-right: rgb(185, 185, 185) 1px solid;
    }
</style>
{% endblock stylesheet %}
{% block content %}
<!--tag_list-->
<div>
    <div class="top_nav">
        <div class="pinterest">
            <a style="color: black;" href="{% url 'myApp:reference_list' %}">from phoing</a>
    
        </div>
        <div class="local">
            <a style="color: black;" href="{% url 'myApp:local_list' %}">from pinterest</a>
        </div>
    </div>
    <div class="grid">
        {% for tag in tags %}
        <div class="grid-item">

            <div class=" item_top tag-{{tag.pk}}">
                <div>
                    <a href="{% url 'myApp:local_detail' tag.tag %}">
                        <p>#{{ tag.tag }}</p>
                    </a>
                </div>
            </div>
            <div class="item_bottom">
                <div class="like like-{{tag.id}}">
                    {% if request_user in tag.like_users.all %}
                    <i class="fas fa-heart" type="submit" onclick="onClickLike({{ tag.id }})" name="type"
                        value="like"></i>
                    {% else %}
                    <i class="far fa-heart" type="submit" onclick="onClickLike({{ tag.id }})" name="type"
                        value="like"></i>
                    {% endif %}
                    <span class="like__content">{{ tag.like_users.count }}</span>
                </div>
                <div class="save save-{{tag.id}}">
                    {% if request_user in tag.save_users.all %}
                    <i class="fas fa-bookmark" type="submit" onclick="onClickSave({{ tag.id }})" name="type"
                        value="save"></i>
                    {% else %}
                    <i class="far fa-bookmark" type="submit" onclick="onClickSave({{ tag.id }})" name="type"
                        value="save"></i>
                    {% endif %}
                    <span class="save__content">{{ tag.save_users.count }}</span>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>

    {% if tags.has_next %}
    <a class="infinite-more-link" href="?page={{ tags.next_page_number }}">
        <div class="loading" style="display: none;">Loading...</div>
    </a>
    {% endif %}
</div>
{% endblock content %}
{% block script %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
<script src="https://unpkg.com/infinite-scroll@4/dist/infinite-scroll.pkgd.min.js"></script>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"
    integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/infinite.min.js' %}"></script>
<script src="{% static 'js/contact.js' %}" defer></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script type="text/javascript"
    src="//dapi.kakao.com/v2/maps/sdk.js?appkey=b6bc437b6340a6a287508c2a0e89a88b&libraries=services"></script>
<script src="{% static 'js/contact/contact_list_map.js' %}"></script>

<script>
    let infinite = new Waypoint.Infinite({
        element: $('.grid')[0],
        items: '.grid-item',
        onBeforePageLoad: function () {
            $('.loading').show();
        },
        onAfterPageLoad: function () {
            $('.loading').hide();
            let msnry = new Masonry('.grid', {
                itemSelector: '.grid-item',
                gutter: 10,
            })
        }
    });
    let msnry = new Masonry('.grid', {
        // optionsW
        itemSelector: '.grid-item',
        gutter: 10,
        // columnWidth: 200
    });
    // like
    const onClickLike = async (tag_id) => {
        try {
            // const url = '/tag/';
            // const {
            //     data
            // } = await axios.post(url, {
            //     tag_id,
            // })
            // modify(data.tag_id, data.is_liked)

            const options = {
                url: '/tag/like/',
                method: 'POST',
                data: {
                    tag_id: tag_id,
                }
            }
            const response = await axios(options)
            const responseOK = response && response.status === 200 && response.statusText === 'OK'
            if (responseOK) {
                const data = response.data
                modifyLike(data.tag_id, data.is_liked)
            }
        } catch (error) {
            console.log(error)
        }
    }

    const modifyLike = (tag_id, is_liked) => {
        const like = document.querySelector(`.like-${tag_id} i`);
        const like_content = document.querySelector(`.like-${tag_id} .like__content`)
        const num = like_content.innerText; // [ {{ tag.like_users.count }} ]
        console.log(num)
        if (is_liked === true) {

            like.className = "fas fa-heart";

            const count = Number(num) + 1;
            like_content.innerHTML = count
        } else {
            like.className = "far fa-heart";

            const count = Number(num) - 1;
            like_content.innerHTML = count
        }

    }


    // save
    const onClickSave = async (tag_id) => {
        try {
            // const url = '/tag/';
            // const {
            //     data
            // } = await axios.post(url, {
            //     tag_id,
            // })
            // modify(data.tag_id, data.is_saved)

            const options = {
                url: '/tag/save/',
                method: 'POST',
                data: {
                    tag_id: tag_id,
                }
            }
            const response = await axios(options)
            const responseOK = response && response.status === 200 && response.statusText === 'OK'
            if (responseOK) {
                const data = response.data
                //modify에서는 이미 뒤집힌 is_saved 값이 들어감!
                modifySave(data.tag_id, data.is_saved)
            }
        } catch (error) {
            console.log(error)
        }
    }

    const modifySave = (tag_id, is_saved) => {
        const save = document.querySelector(`.save-${tag_id} i`);
        const save_content = document.querySelector(`.save-${tag_id} .save__content`)
        const num = save_content.innerText; // [ {{ tag.save_users.count }} ]
        console.log(num)
        if (is_saved === true) {

            save.className = "fas fa-bookmark";

            const count = Number(num) + 1;
            save_content.innerHTML = count
        } else {
            save.className = "far fa-bookmark";

            const count = Number(num) - 1;
            save_content.innerHTML = count
        }

    }
</script>


{% endblock script %}