phoing/chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/home/', views.chat_home, name='chat_home'),
    path('pending/', views.chat_add_pendings, name='chat_add_pendings'),
    path('member/', views.chat_add_members, name='chat_add_members'),
    path('reject/', views.chat_add_rejected, name='chat_add_rejected'),
    path('<str:room_name>/', views.chat_room, name='room'),
   
]

phoing/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('user.urls')),
    path('', include('myApp.urls')),
    path('place/', include('place.urls')),
    path('chat/', include('chat.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

phoing/myApp/urls.py
from django.urls import path
from . import views

app_name = 'myApp'

urlpatterns = [
     path('login/general_login', view=views.general_login, name='general_login'),
    #####################profile#######################
    path('', view=views.main_list, name='main_list'),
    path('profile/<int:pk>/', view=views.profile_detail, name='profile_detail'),
    path('profile/<int:pk>/posts/',
         view=views.profile_detail_posts, name='profile_detail_posts'),
     path('profile/<int:pk>/saves/',
         view=views.profile_detail_saves, name='profile_detail_saves'),
    path('profile/<int:pk>/delete/',
         view=views.profile_delete, name='profile_delete'),
    path('profile/<int:pk>/update/',
         view=views.profile_update, name='profile_update'),
    path('profile/<int:pk>/profile_update_password/',
         view=views.profile_update_password, name='profile_update_password'),
    path('profile/create/', view=views.profile_create, name='profile_create'),
    path('profile/post/create/', view=views.post_create, name='post_create'),

    #####################contact#######################
    path('contact/', view=views.contact_list, name='contact_list'),
    #path('contact/<string:category>', view=views.contact_category, name='contact_category'),
    path('contact/map/', view=views.contact_map, name='contact_map'),
    path('contact/detail/<int:pk>/',
         view=views.contact_detail, name='contact_detail'),
    path('contact/<int:pk>/comment_create/',
         view=views.contact_comment_create, name='contact_comment_create'),
    path('contact/<int:pk>/comment_delete/',
         view=views.contact_comment_delete, name='contact_comment_delete'),
    path('contact/<int:pk>/delete/',
         view=views.contact_delete, name='contact_delete'),
    path('contact/<int:pk>/update/',
         view=views.contact_update, name='contact_update'),
    path('contact/create/', view=views.contact_create, name='contact_create'),
    path('contact/save/', views.contact_save, name='contact_save'),

    #####################portfolio#######################
    path('portfolio/',
         view=views.portfolio_list, name='portfolio_list'),
    path('portfolio/<int:pk>/', view=views.portfolio_detail,
         name='portfolio_detail'),
    path('portfolio/<int:pk>/delete/',
         view=views.portfolio_delete, name='portfolio_delete'),
    path('portfolio/<int:pk>/update/',
         view=views.portfolio_update, name='portfolio_update'),
    path('portfolio/create/', view=views.portfolio_create, name='portfolio_create'),
    path('portfolio/like/', view=views.portfolio_like,
         name='portfolio_like'),
    path('portfolio/save/', view=views.portfolio_save,
         name='portfolio_save'),

    #####################reference#######################
    #1. from phoging(local) #
    path('local/', view=views.local_list, name='local_list'),
    path('local/<slug:tag>/', view=views.local_detail, name='local_detail'),


    #2. from reference(pinterest) #
    path('reference/', view=views.reference_list, name='reference_list'),
    path('reference/detail/<int:pk>/',
         view=views.reference_detail, name='reference_detail'),

    #####################collaborations#######################

    #1. with brand #
    path('with_brand/', view=views.with_brand_list, name='with_brand_list'),
    #path('with_brand/<string:category>', view=views.with_brand_category, name='with_brand_category'),
    path('with_brand/map/', view=views.with_brand_map, name='with_brand_map'),
    path('with_brand/detail/<int:pk>/',
         view=views.with_brand_detail, name='with_brand_detail'),
    path('with_brand/<int:pk>/comment_create/',
         view=views.with_brand_comment_create, name='with_brand_comment_create'),
    path('with_brand/<int:pk>/comment_delete/',
         view=views.with_brand_comment_delete, name='with_brand_comment_delete'),
    path('with_brand/<int:pk>/delete/',
         view=views.with_brand_delete, name='with_brand_delete'),
    path('with_brand/<int:pk>/update/',
         view=views.with_brand_update, name='with_brand_update'),
    path('with_brand/create/', view=views.with_brand_create,
         name='with_brand_create'),
    path('with_brand/save/', view=views.with_brand_save, name='with_brand_save'),

    #2. with artist #
    path('with_artist/', view=views.with_artist_list, name='with_artist_list'),
    #path('with_artist/<str2aing:category>', view=views.with_artist_category, name='with_artist_category'),
    path('with_artist/map/', view=views.with_artist_map,
         name='with_artist_map'),
    path('with_artist/detail/<int:pk>/',
         view=views.with_artist_detail, name='with_artist_detail'),
    path('with_artist/<int:pk>/comment_create/',
         view=views.with_artist_comment_create, name='with_artist_comment_create'),
    path('with_artist/<int:pk>/comment_delete/',
         view=views.with_artist_comment_delete, name='with_artist_comment_delete'),
    path('with_artist/<int:pk>/delete/',
         view=views.with_artist_delete, name='with_artist_delete'),
    path('with_artist/<int:pk>/update/',
         view=views.with_artist_update, name='with_artist_update'),
    path('with_artist/create/', view=views.with_artist_create,
         name='with_artist_create'),
    path('with_artist/save/', view=views.with_artist_save,
         name='with_artist_save'),

]

phoing/place/urls.py
from django.urls import path
from . import views

app_name = 'place'

urlpatterns = [
    #####################profile#######################
    path('', view=views.place_list, name='place_list'),
    path('map/', view=views.place_map, name='place_map'),
    path('create/', view=views.place_create, name='place_create'),
    path('detail/<int:pk>/',
         view=views.place_detail, name='place_detail'),
    path('<int:pk>/delete/',
         view=views.place_delete, name='place_delete'),
    path('<int:pk>/update/',
         view=views.place_update, name='place_update'),

    path('select/', view=views.place_select,
         name='place_select'),  # TODO : 나중에 삭제할 것


    # path('<int:pk>/comment_create/',
    #      view=views.place_comment_create, name='place_comment_create'),
    # path('<int:pk>/comment_delete/',
    #      view=views.place_comment_delete, name='place_comment_delete'),
    # path('save/', views.place_save, name='place_save'),

]

phoing/myApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http.response import HttpResponse
from .forms import *
from user.models import *
from .models import *
import random
from django.http import JsonResponse

# for SAVE, LIKE
import json
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.contrib.auth import login as auth_login
from .utils import *
from place.forms import LocationForm

# category filteringx
from django.db.models import Count, Q

# infinite loading
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# for multiple images
from django.forms import modelformset_factory

# for change password
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
# web chat
from chat.models import *

def main_list(request):
    ctx = {}
    return render(request, 'myApp/main/main_list.html', context=ctx)

###################### profile section ######################



###################### portfolio section ######################

# @api_view(['GET'])
def portfolio_list(request):
    portfolios = Portfolio.objects.all().order_by("?")
    request_user = request.user

    # category 분류 # order_by("?"): random 으로 선택
    category = request.GET.get('category', 'all')

    if category != 'all':
        if category == User.CATEGORY_PHOTOGRAPHER:
            portfolios = portfolios.filter(Q(user__category=User.CATEGORY_PHOTOGRAPHER)
                                           ).distinct().order_by("?")
        elif category == User.CATEGORY_MODEL:
            portfolios = portfolios.filter(Q(user__category=User.CATEGORY_MODEL)
                                           ).distinct().order_by("?")
        elif category == User.CATEGORY_HM:
            portfolios = portfolios.filter(Q(user__category=User.CATEGORY_HM)
                                           ).distinct().order_by("?")
        elif category == User.CATEGORY_STYLIST:
            portfolios = portfolios.filter(Q(user__category=User.CATEGORY_STYLIST)
                                           ).distinct().order_by("?")
        elif category == User.CATEGORY_OTHERS:
            portfolios = portfolios.filter(Q(user__category=User.CATEGORY_OTHERS)
                                           ).distinct().order_by("?")

    # SORT 최신순, 조회순, 좋아요순, 저장순
    sort = request.GET.get('sort', 'recent')

    if sort == 'recent':
        portfolios = portfolios.order_by('-updated_at')
    elif sort == 'view':
        portfolios = portfolios.annotate(num_save=Count(
            'view_count')).order_by('-num_save', '-updated_at')
    elif sort == 'like':
        portfolios = portfolios.annotate(num_save=Count(
            'like_users')).order_by('-num_save', '-updated_at')
    elif sort == 'save':
        portfolios = portfolios.annotate(num_save=Count(
            'save_users')).order_by('-num_save', '-updated_at')

    # infinite scroll
    portfolios_per_page = 6
    page = request.GET.get('page', 1)
    paginator = Paginator(portfolios, portfolios_per_page)
    try:
        portfolios = paginator.page(page)
    except PageNotAnInteger:
        portfolios = paginator.page(1)
    except EmptyPage:
        portfolios = paginator.page(paginator.num_pages)

    context = {'portfolios': portfolios, 'request_user': request.user, 'sort': sort,
               'category': category, }
    return render(request, 'myApp/portfolio/portfolio_list.html', context=context)


def portfolio_detail(request, pk):
    portfolio = Portfolio.objects.get(pk=pk)
    images = portfolio.portfolio_images.all()
    num_of_imgs = images.count

    tags = portfolio.tags.all()

    portfolio_owner = portfolio.user  # 게시글 작성자
    request_user = request.user  # 로그인한 유저

    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    print(ip)

    # 조회수

    try: 
        view_counts=ViewCount.objects.get(ip=ip, post=portfolio)
    except Exception as e:
        print(e)
        view_counts=ViewCount(ip=ip, post=portfolio)
        Portfolio.objects.filter(pk=pk).update(view_count=portfolio.view_count+1)
        view_counts.save()
    else:
        if not view_counts.date == timezone.localtime().date():
            Portfolio.objects.filter(pk=pk).update(view_count=portfolio.view_count+1)
            view_counts.date=timezone.localtime()
            view_counts.save()
        else:
            print(str()+'has already hit his post.\n\n')



    ctx = {'portfolio': portfolio,
           'images': images,
           'tags': tags,
           'portfolio_owner': portfolio_owner,
           'request_user': request_user,
           'num_of_imgs': num_of_imgs, }
    return render(request, 'myApp/portfolio/portfolio_detail.html', context=ctx)


@login_required
def portfolio_delete(request, pk):
    portfolio = Portfolio.objects.get(pk=pk)
    owner = portfolio.user
    if request.method == 'POST':
        portfolio.delete()
        messages.success(request, "삭제되었습니다.")
        return redirect('myApp:profile_detail_posts', owner.id)
    else:
        ctx = {'portfolio': portfolio}
        return render(request, 'myApp/portfolio/portfolio_delete.html', context=ctx)


@login_required
def portfolio_update(request, pk):
    portfolio = get_object_or_404(Portfolio, pk=pk)
    if request.method == 'POST':
        form = PortfolioForm(request.POST, request.FILES, instance=portfolio)
        if form.is_valid():
            portfolio = form.save(commit=False)
            portfolio.user = request.user
            portfolio.save()
            portfolio.image = request.FILES.get('image')

            portfolio.tags.all().delete()

            # save tag
            tags = Tag.add_tags(portfolio.tag_str)
            for tag in tags:
                portfolio.tags.add(tag)

            return redirect('myApp:portfolio_detail', portfolio.id)
    else:
        form = PortfolioForm(instance=portfolio)
        ctx = {'form': form,}
        return render(request, 'myApp/portfolio/portfolio_update.html', ctx)


@login_required
def portfolio_create(request):
    ImageFormSet = modelformset_factory(Images, form=ImageForm, extra=10)
    # 'extra' : number of photos
    if request.method == 'POST':
        form = PortfolioForm(request.POST, request.FILES,)
        formset = ImageFormSet(request.POST, request.FILES,
                               queryset=Images.objects.none())

        if form.is_valid() and formset.is_valid():
            portfolio = form.save(commit=False)
            portfolio.user = request.user
            portfolio.save()
            portfolio.image = request.FILES.get('image')
            for form in formset.cleaned_data:
                if form:
                    image = form['image']
                    
                    photo = Images(portfolio=portfolio, image=image)
                    photo.save()
            messages.success(request, "posted!")

            # # prev_tag
            # prev_tags = Tag.objects.all()
            # save tag
            tags_portfolio = Tag.add_tags(portfolio.tag_str)
            for tag in tags_portfolio:
                portfolio.tags.add(tag)

            # # tag compare
            # # tags_portfolio의 tag가 tag_all에 있는지 확인하고
            # # 이미 있으면 do nothing
            # # 없으면 tag 게시물 create
            # local_create(request, prev_tags)

            return redirect('myApp:portfolio_detail', portfolio.pk)
        else:
            print(form.errors, formset.errors)

    else:
        form = PortfolioForm()
        formset = ImageFormSet(queryset=Images.objects.none())
        ctx = {'form': form, 'formset': formset}

    return render(request, 'myApp/portfolio/portfolio_create.html', ctx)


@csrf_exempt
def portfolio_save(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        portfolio_id = data["portfolio_id"]
        portfolio = get_object_or_404(Portfolio, pk=portfolio_id)
        request_user = request.user
        is_saved = request_user in portfolio.save_users.all()
        if is_saved:
            portfolio.save_users.remove(
                get_object_or_404(User, pk=request_user.pk))
        else:
            portfolio.save_users.add(
                get_object_or_404(User, pk=request_user.pk))
        is_saved = not is_saved
        portfolio.save()
        return JsonResponse({'portfolio_id': portfolio_id, 'is_saved': is_saved})


@csrf_exempt
def portfolio_like(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        portfolio_id = data["portfolio_id"]
        portfolio = get_object_or_404(Portfolio, pk=portfolio_id)
        request_user = request.user
        is_liked = request_user in portfolio.like_users.all()
        if is_liked:
            portfolio.like_users.remove(
                get_object_or_404(User, pk=request_user.pk))
        else:
            portfolio.like_users.add(
                get_object_or_404(User, pk=request_user.pk))
        is_liked = not is_liked
        portfolio.save()
        return JsonResponse({'portfolio_id': portfolio_id, 'is_liked': is_liked})


# TODO view_count 수정
@csrf_exempt
def portfolio_view(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        portfolio_id = data["portfolio_id"]
        portfolio = get_object_or_404(Portfolio, pk=portfolio_id)
        request_user = request.user
        is_viewed = request_user in portfolio.view_count.all()
        portfolio.save_users.add(get_object_or_404(User, pk=request_user.pk))
        is_saved = not is_saved
        portfolio.save()
        return JsonResponse({'portfolio_id': portfolio_id, 'is_saved': is_saved})

phoing/myApp/templates/myApp/layout.html
{% load static %}
{% load poll_extras %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PHOING</title>
  {% block stylesheet %}{% endblock %}

  <script src="https://kit.fontawesome.com/0b02921f0e.js" crossorigin="anonymous"></script>
  <script src="{% static 'js/main.js' %}" defer></script>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Serif&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link
    href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap"
    rel="stylesheet">


  <!-- <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/moonspam/NanumSquare@1.0/nanumsquare.css">
    <style>
        * {
            font-family: 'NanumSquare', sans-serif;
        }
    </style>-->
  <style>
    body {
      overflow-x: hidden
    }

    /*LOADING*/
    #loading {
      width: 100%;
      height: 100%;
      background: #fff;
      z-index: 1000;
      /* 이 값으로 레이어의 위치를 조정합니다. */
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      background-size: cover;
      font-family: "Cabin Condensed", sans-serif;
    }

    @import url(https://fonts.googleapis.com/css?family=Cabin+Condensed);

    svg {
      font-weight: bold;
      max-width: 600px;
      height: 100%;
    }

    /*CSS*/

    * {
      margin: 0;
      padding: 0;
      text-decoration: none;
      list-style-type: none;
      font-family: "NanumSquare", sans-serif;
      box-sizing: border-box;
      scroll-behavior: smooth;
    }

    nav {
      background-color: #fff;
    }

    nav a {
      color: black;
    }

    .content {
      display: block;
      margin: 0 auto;
    }

    #nav {
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-bottom: 1px solid rgb(54, 54, 54);
      padding: 15px 15px;
      position: sticky;
      /* Set the navbar to fixed position */
      top: 0;
      /* Position the navbar at the top of the page */
      width: 100%;
      /* Full width */
      background-color: #FFF;
      z-index: 1;
    }

    .nav_left {
      display: flex;
    }

    .nav__profile {
      display: flex;
      align-items: center;
    }


    .nav__logo {
      display: flex;
      align-items: center;
      font-size: 24px;
    }

    .nav__menu {
      display: flex;
      padding-left: 20px;
    }

    .nav__menu li {
      display: flex;
      align-items: center;
      padding-right: 20px;
    }


    .nav__profile li {
      display: flex;
      align-items: center;
      padding-right: 20px;

    }

    .nav__profile .padding {
      padding-right: 5px;
    }

    .nav__menu li a:hover {
      color: purple;
      cursor: pointer;
    }



    .nav__profile i {
      font-size: 20px;
    }

    .nav__profile a:hover i {
      color: purple;
      cursor: pointer;
    }

    .nav__toggleBtn {
      display: none;

      font-size: 24px;
    }

    @media screen and (max-width: 820px) {

      .nav__menu {
        display: none;
        flex-direction: column;
        align-items: center;
        width: 100%;
      }

      .nav__menu li {
        width: 100%;
        text-align: center;
        padding-left: 0;
      }

      .nav__profile {
        display: none;
      }

      .nav__toggleBtn {
        display: flex;
        justify-content: flex-end;

      }

      .nav__menu.active {
        display: block;
      }

      .nav__profile.active {
        display: block;
      }
    }



    #footer {
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-top: 1px solid rgb(54, 54, 54);
      padding: 15px 30px;
      font-size: 13px;
      margin-top: 20px;
    }

    footer li,
    footer a {
      color: rgb(0, 0, 0);
    }

    .footer__logo {
      font-size: 15px;
      padding-bottom: 8px;
    }

    .footer__right {
      display: flex;
      cursor: pointer;
    }

    .footer__right li {
      padding: 8px 10px;
    }

    .footer__right i {
      font-size: 30px;
    }

    .footer__right li:hover,
    .footer__right a:hover {
      color: purple;
    }

    /*LOADING*/
    #loading {
      width: 100%;
      height: 100%;
      background: #fff;
      z-index: 1000;
      /* 이 값으로 레이어의 위치를 조정합니다. */
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      background-size: cover;
      font-family: "Cabin Condensed", sans-serif;
    }

    @import url(https://fonts.googleapis.com/css?family=Cabin+Condensed);


    /**/

    * {
      scroll-behavior: smooth;
    }

    /* SCROLL */
    ::-webkit-scrollbar {
      width: 8px;
    }

    /* 스크롤바의 width */
    ::-webkit-scrollbar-track {
      background-color: #fafafa;
    }

    /* 스크롤바의 전체 배경색 */
    ::-webkit-scrollbar-thumb {
      background: linear-gradient(to bottom, #000000, #b6b6b6);
      border-radius: 20px;
    }

    /* 스크롤바 색 */
    ::-webkit-scrollbar-button {
      display: none;
    }

    .here {
      background: none;
      border: none;
      font-family: "NanumSquare", sans-serif;
      font-size: 16px;
    }

    .here:active {
      cursor: pointer;
    }

    .here:focus {
      outline: 0;
    }

    /* 위 아래 버튼 (버튼 없애기를 함) */
  </style>




</head>

<body>


  <!-- <div id="loading">
        <svg viewbox="0 0 100 20">
            <defs>
                <linearGradient id="gradient">
                <stop color="#000"/>
                </linearGradient>
                <pattern id="wave" x="0" y="-0.5" width="100%" height="100%" patternUnits="userSpaceOnUse">
                <path id="wavePath" d="M-40 9 Q-30 7 -20 9 T0 9 T20 9 T40 9 T60 9 T80 9 T100 9 T120 9 V20 H-40z" mask="url(#mask)" fill="url(#gradient)"> 
                    <animateTransform
                        attributeName="transform"
                        begin="0s"
                        dur="1.5s"
                        type="translate"
                        from="0,0"
                        to="40,0"
                        repeatCount="indefinite" />
                </path>
                </pattern>
            </defs>
            <text text-anchor="middle" x="50" y="15" font-size="14" fill="white" fill-opacity="0.1">LOADING</text>
            <text text-anchor="middle" x="50" y="15" font-size="14" fill="url(#wave)"  fill-opacity="1">LOADING</text>
            </svg>  
    </div> -->


  <head>
    <nav id="nav">
      <div class="nav_left">
        <div class="nav__logo">
          <a href="{% url 'myApp:main_list' %}"><i class="fas fa-camera"></i> PHOING</a>
        </div>
        <ul class="nav__menu">
          <li><a href="{% url 'myApp:contact_list' %}">Contact</a></li>
          <li><a href="{% url 'myApp:portfolio_list' %}">Portfolio</a></li>
          <li><a href="{% url 'myApp:reference_list' %}">Reference</a></li>
          <li><a href="{% url 'place:place_list' %}">Place</a></li>
          <li><a href="{% url 'myApp:with_brand_list' %}">Collaboration</a></li>
        </ul>
      </div>

      <ul class="nav__profile" style="float: right;">

        {% if not user.is_authenticated %}

        <li><a href="{% url 'account_login' %}?next={{ request.path }}">Log In/Sign Up</a></li>
        <li><a href="{% url 'account_login' %}">My profile&nbsp;<i class="far fa-user-circle"></i></a></li>
        {% else %}
        {% url 'myApp:profile_detail' user.id as profile_path %}


        <li><a href="{% url 'chat:chat_home' request.user.pk %}">Messages</a></li>

        <form method="post" action="{% url 'account_logout' %}">
          {% csrf_token %}
          {% if redirect_field_value %}
          <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
          {% endif %}
          <input class="here" type="submit" value="Log Out" onclick="return confirm('Are you sure?');"
            style="margin-right: 10px;"></input>
        </form>

        <li><a href=" {% url 'myApp:profile_detail' user.id %}">My profile&nbsp;<i class="far fa-user-circle"></i></a>
        </li>

        {% endif %}

      </ul>
      <a href="#" class="nav__toggleBtn"><i class="fas fa-bars"></i></a>
    </nav>
  </head>
  <section class="container">
    {% block content %}
    {% endblock %}
  </section>
  <footer id="footer">
    <ul class="footer__left">
      <li class="footer__logo">PHOING</li>
      <li>Copyright PHOING All right reserved</li>
      <li><a href="#">개인정보처리방침</a></li>
    </ul>
    <ul class="footer__right">
      <li><i class="fab fa-instagram"></i></li>
      <li><i class="fab fa-facebook-square"></i></li>
      <li><i class="fab fa-youtube-square"></i></li>
    </ul>
  </footer>
  {% block script %}
  {% endblock script%}
</body>

</html>