phoing/chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/home/', views.chat_home, name='chat_home'),
    path('pending/', views.chat_add_pendings, name='chat_add_pendings'),
    path('member/', views.chat_add_members, name='chat_add_members'),
    path('reject/', views.chat_add_rejected, name='chat_add_rejected'),
    path('<str:room_name>/', views.chat_room, name='room'),
   
]

phoing/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('user.urls')),
    path('', include('myApp.urls')),
    path('place/', include('place.urls')),
    path('chat/', include('chat.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

phoing/myApp/urls.py
from django.urls import path
from . import views

app_name = 'myApp'

urlpatterns = [
     path('login/general_login', view=views.general_login, name='general_login'),
    #####################profile#######################
    path('', view=views.main_list, name='main_list'),
    path('profile/<int:pk>/', view=views.profile_detail, name='profile_detail'),
    path('profile/<int:pk>/posts/',
         view=views.profile_detail_posts, name='profile_detail_posts'),
     path('profile/<int:pk>/saves/',
         view=views.profile_detail_saves, name='profile_detail_saves'),
    path('profile/<int:pk>/delete/',
         view=views.profile_delete, name='profile_delete'),
    path('profile/<int:pk>/update/',
         view=views.profile_update, name='profile_update'),
    path('profile/<int:pk>/profile_update_password/',
         view=views.profile_update_password, name='profile_update_password'),
    path('profile/create/', view=views.profile_create, name='profile_create'),
    path('profile/post/create/', view=views.post_create, name='post_create'),

    #####################contact#######################
    path('contact/', view=views.contact_list, name='contact_list'),
    #path('contact/<string:category>', view=views.contact_category, name='contact_category'),
    path('contact/map/', view=views.contact_map, name='contact_map'),
    path('contact/detail/<int:pk>/',
         view=views.contact_detail, name='contact_detail'),
    path('contact/<int:pk>/comment_create/',
         view=views.contact_comment_create, name='contact_comment_create'),
    path('contact/<int:pk>/comment_delete/',
         view=views.contact_comment_delete, name='contact_comment_delete'),
    path('contact/<int:pk>/delete/',
         view=views.contact_delete, name='contact_delete'),
    path('contact/<int:pk>/update/',
         view=views.contact_update, name='contact_update'),
    path('contact/create/', view=views.contact_create, name='contact_create'),
    path('contact/save/', views.contact_save, name='contact_save'),

    #####################portfolio#######################
    path('portfolio/',
         view=views.portfolio_list, name='portfolio_list'),
    path('portfolio/<int:pk>/', view=views.portfolio_detail,
         name='portfolio_detail'),
    path('portfolio/<int:pk>/delete/',
         view=views.portfolio_delete, name='portfolio_delete'),
    path('portfolio/<int:pk>/update/',
         view=views.portfolio_update, name='portfolio_update'),
    path('portfolio/create/', view=views.portfolio_create, name='portfolio_create'),
    path('portfolio/like/', view=views.portfolio_like,
         name='portfolio_like'),
    path('portfolio/save/', view=views.portfolio_save,
         name='portfolio_save'),

    #####################reference#######################
    #1. from phoging(local) #
    path('local/', view=views.local_list, name='local_list'),
    path('local/<slug:tag>/', view=views.local_detail, name='local_detail'),


    #2. from reference(pinterest) #
    path('reference/', view=views.reference_list, name='reference_list'),
    path('reference/detail/<int:pk>/',
         view=views.reference_detail, name='reference_detail'),

    #####################collaborations#######################

    #1. with brand #
    path('with_brand/', view=views.with_brand_list, name='with_brand_list'),
    #path('with_brand/<string:category>', view=views.with_brand_category, name='with_brand_category'),
    path('with_brand/map/', view=views.with_brand_map, name='with_brand_map'),
    path('with_brand/detail/<int:pk>/',
         view=views.with_brand_detail, name='with_brand_detail'),
    path('with_brand/<int:pk>/comment_create/',
         view=views.with_brand_comment_create, name='with_brand_comment_create'),
    path('with_brand/<int:pk>/comment_delete/',
         view=views.with_brand_comment_delete, name='with_brand_comment_delete'),
    path('with_brand/<int:pk>/delete/',
         view=views.with_brand_delete, name='with_brand_delete'),
    path('with_brand/<int:pk>/update/',
         view=views.with_brand_update, name='with_brand_update'),
    path('with_brand/create/', view=views.with_brand_create,
         name='with_brand_create'),
    path('with_brand/save/', view=views.with_brand_save, name='with_brand_save'),

    #2. with artist #
    path('with_artist/', view=views.with_artist_list, name='with_artist_list'),
    #path('with_artist/<str2aing:category>', view=views.with_artist_category, name='with_artist_category'),
    path('with_artist/map/', view=views.with_artist_map,
         name='with_artist_map'),
    path('with_artist/detail/<int:pk>/',
         view=views.with_artist_detail, name='with_artist_detail'),
    path('with_artist/<int:pk>/comment_create/',
         view=views.with_artist_comment_create, name='with_artist_comment_create'),
    path('with_artist/<int:pk>/comment_delete/',
         view=views.with_artist_comment_delete, name='with_artist_comment_delete'),
    path('with_artist/<int:pk>/delete/',
         view=views.with_artist_delete, name='with_artist_delete'),
    path('with_artist/<int:pk>/update/',
         view=views.with_artist_update, name='with_artist_update'),
    path('with_artist/create/', view=views.with_artist_create,
         name='with_artist_create'),
    path('with_artist/save/', view=views.with_artist_save,
         name='with_artist_save'),

]

phoing/myApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http.response import HttpResponse
from .forms import *
from user.models import *
from .models import *
import random
from django.http import JsonResponse

# for SAVE, LIKE
import json
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.contrib.auth import login as auth_login
from .utils import *
from place.forms import LocationForm

# category filteringx
from django.db.models import Count, Q

# infinite loading
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# for multiple images
from django.forms import modelformset_factory

# for change password
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
# web chat
from chat.models import *

def main_list(request):
    ctx = {}
    return render(request, 'myApp/main/main_list.html', context=ctx)

###################### profile section ######################



###################### portfolio section ######################

# @api_view(['GET'])
def portfolio_list(request):
    portfolios = Portfolio.objects.all().order_by("?")
    request_user = request.user

    # category 분류 # order_by("?"): random 으로 선택
    category = request.GET.get('category', 'all')

    if category != 'all':
        if category == User.CATEGORY_PHOTOGRAPHER:
            portfolios = portfolios.filter(Q(user__category=User.CATEGORY_PHOTOGRAPHER)
                                           ).distinct().order_by("?")
        elif category == User.CATEGORY_MODEL:
            portfolios = portfolios.filter(Q(user__category=User.CATEGORY_MODEL)
                                           ).distinct().order_by("?")
        elif category == User.CATEGORY_HM:
            portfolios = portfolios.filter(Q(user__category=User.CATEGORY_HM)
                                           ).distinct().order_by("?")
        elif category == User.CATEGORY_STYLIST:
            portfolios = portfolios.filter(Q(user__category=User.CATEGORY_STYLIST)
                                           ).distinct().order_by("?")
        elif category == User.CATEGORY_OTHERS:
            portfolios = portfolios.filter(Q(user__category=User.CATEGORY_OTHERS)
                                           ).distinct().order_by("?")

    # SORT 최신순, 조회순, 좋아요순, 저장순
    sort = request.GET.get('sort', 'recent')

    if sort == 'recent':
        portfolios = portfolios.order_by('-updated_at')
    elif sort == 'view':
        portfolios = portfolios.annotate(num_save=Count(
            'view_count')).order_by('-num_save', '-updated_at')
    elif sort == 'like':
        portfolios = portfolios.annotate(num_save=Count(
            'like_users')).order_by('-num_save', '-updated_at')
    elif sort == 'save':
        portfolios = portfolios.annotate(num_save=Count(
            'save_users')).order_by('-num_save', '-updated_at')

    # infinite scroll
    portfolios_per_page = 6
    page = request.GET.get('page', 1)
    paginator = Paginator(portfolios, portfolios_per_page)
    try:
        portfolios = paginator.page(page)
    except PageNotAnInteger:
        portfolios = paginator.page(1)
    except EmptyPage:
        portfolios = paginator.page(paginator.num_pages)

    context = {'portfolios': portfolios, 'request_user': request.user, 'sort': sort,
               'category': category, }
    return render(request, 'myApp/portfolio/portfolio_list.html', context=context)


def portfolio_detail(request, pk):
    portfolio = Portfolio.objects.get(pk=pk)
    images = portfolio.portfolio_images.all()
    num_of_imgs = images.count

    tags = portfolio.tags.all()

    portfolio_owner = portfolio.user  # 게시글 작성자
    request_user = request.user  # 로그인한 유저

    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    print(ip)

    # 조회수

    try: 
        view_counts=ViewCount.objects.get(ip=ip, post=portfolio)
    except Exception as e:
        print(e)
        view_counts=ViewCount(ip=ip, post=portfolio)
        Portfolio.objects.filter(pk=pk).update(view_count=portfolio.view_count+1)
        view_counts.save()
    else:
        if not view_counts.date == timezone.localtime().date():
            Portfolio.objects.filter(pk=pk).update(view_count=portfolio.view_count+1)
            view_counts.date=timezone.localtime()
            view_counts.save()
        else:
            print(str()+'has already hit his post.\n\n')



    ctx = {'portfolio': portfolio,
           'images': images,
           'tags': tags,
           'portfolio_owner': portfolio_owner,
           'request_user': request_user,
           'num_of_imgs': num_of_imgs, }
    return render(request, 'myApp/portfolio/portfolio_detail.html', context=ctx)


@login_required
def portfolio_delete(request, pk):
    portfolio = Portfolio.objects.get(pk=pk)
    owner = portfolio.user
    if request.method == 'POST':
        portfolio.delete()
        messages.success(request, "삭제되었습니다.")
        return redirect('myApp:profile_detail_posts', owner.id)
    else:
        ctx = {'portfolio': portfolio}
        return render(request, 'myApp/portfolio/portfolio_delete.html', context=ctx)


@login_required
def portfolio_update(request, pk):
    portfolio = get_object_or_404(Portfolio, pk=pk)
    if request.method == 'POST':
        form = PortfolioForm(request.POST, request.FILES, instance=portfolio)
        if form.is_valid():
            portfolio = form.save(commit=False)
            portfolio.user = request.user
            portfolio.save()
            portfolio.image = request.FILES.get('image')

            portfolio.tags.all().delete()

            # save tag
            tags = Tag.add_tags(portfolio.tag_str)
            for tag in tags:
                portfolio.tags.add(tag)

            return redirect('myApp:portfolio_detail', portfolio.id)
    else:
        form = PortfolioForm(instance=portfolio)
        ctx = {'form': form,}
        return render(request, 'myApp/portfolio/portfolio_update.html', ctx)


@login_required
def portfolio_create(request):
    ImageFormSet = modelformset_factory(Images, form=ImageForm, extra=10)
    # 'extra' : number of photos
    if request.method == 'POST':
        form = PortfolioForm(request.POST, request.FILES,)
        formset = ImageFormSet(request.POST, request.FILES,
                               queryset=Images.objects.none())

        if form.is_valid() and formset.is_valid():
            portfolio = form.save(commit=False)
            portfolio.user = request.user
            portfolio.save()
            portfolio.image = request.FILES.get('image')
            for form in formset.cleaned_data:
                if form:
                    image = form['image']
                    
                    photo = Images(portfolio=portfolio, image=image)
                    photo.save()
            messages.success(request, "posted!")

            # # prev_tag
            # prev_tags = Tag.objects.all()
            # save tag
            tags_portfolio = Tag.add_tags(portfolio.tag_str)
            for tag in tags_portfolio:
                portfolio.tags.add(tag)

            # # tag compare
            # # tags_portfolio의 tag가 tag_all에 있는지 확인하고
            # # 이미 있으면 do nothing
            # # 없으면 tag 게시물 create
            # local_create(request, prev_tags)

            return redirect('myApp:portfolio_detail', portfolio.pk)
        else:
            print(form.errors, formset.errors)

    else:
        form = PortfolioForm()
        formset = ImageFormSet(queryset=Images.objects.none())
        ctx = {'form': form, 'formset': formset}

    return render(request, 'myApp/portfolio/portfolio_create.html', ctx)


@csrf_exempt
def portfolio_save(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        portfolio_id = data["portfolio_id"]
        portfolio = get_object_or_404(Portfolio, pk=portfolio_id)
        request_user = request.user
        is_saved = request_user in portfolio.save_users.all()
        if is_saved:
            portfolio.save_users.remove(
                get_object_or_404(User, pk=request_user.pk))
        else:
            portfolio.save_users.add(
                get_object_or_404(User, pk=request_user.pk))
        is_saved = not is_saved
        portfolio.save()
        return JsonResponse({'portfolio_id': portfolio_id, 'is_saved': is_saved})


@csrf_exempt
def portfolio_like(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        portfolio_id = data["portfolio_id"]
        portfolio = get_object_or_404(Portfolio, pk=portfolio_id)
        request_user = request.user
        is_liked = request_user in portfolio.like_users.all()
        if is_liked:
            portfolio.like_users.remove(
                get_object_or_404(User, pk=request_user.pk))
        else:
            portfolio.like_users.add(
                get_object_or_404(User, pk=request_user.pk))
        is_liked = not is_liked
        portfolio.save()
        return JsonResponse({'portfolio_id': portfolio_id, 'is_liked': is_liked})


# TODO view_count 수정
@csrf_exempt
def portfolio_view(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        portfolio_id = data["portfolio_id"]
        portfolio = get_object_or_404(Portfolio, pk=portfolio_id)
        request_user = request.user
        is_viewed = request_user in portfolio.view_count.all()
        portfolio.save_users.add(get_object_or_404(User, pk=request_user.pk))
        is_saved = not is_saved
        portfolio.save()
        return JsonResponse({'portfolio_id': portfolio_id, 'is_saved': is_saved})

phoing/myApp/templates/myApp/profile/post_create.html
{% extends 'myApp/layout.html' %}

{% load static %}

{% block content %}
<div class="container">
    <div class="post_create">
        <h1>Create Your Post</h1><br>
        <a href="{% url 'myApp:contact_create'%}">Contact</a>
        <a href="{% url 'myApp:portfolio_create'%}">Portfolio</a>
    </div>
</div>
{% endblock content%}

phoing/myApp/templates/myApp/profile/profile_create.html
{% extends 'myApp/layout.html' %}
{% block stylesheet %}
<style>
    *{
        margin: 0;
        padding: 0;
        text-decoration: none;
        list-style-type: none;
    }
    label{
        font-size:1.1rem;
    }

    .form-group{
        margin:20px 60px;
        display: grid;
        grid-template-columns: 200px 1fr;
    }

    


   .username input,
   .first_name input,
   .last_name input,
   .email input,
   .category input,
   .password1 input,
   .password2 input {
    border:0; 
    padding:1px; 
    font-size:1.1em; 
    border:solid 1px #ccc; 
    margin-top:4px; 
    width:80%;
    border-radius: 3px;
   }

   .username input:focus,
   .first_name input:focus,
   .last_name input:focus,
   .email input:focus,
   .category input:focus,
   .password1 input:focus,
   .password2 input:focus { 
    outline: none !important;
    border-color: #000000;
    box-shadow: 0 0 10px #000000;
   }

   select{
    border:0; 
    padding:1px; 
    font-size:1.0rem; 
    border:solid 1px #ccc; 
    margin-top:5px; 
    width:50%;
    border-radius: 3px;
   }

   input.btn {
    position: absolute;
    left:72%;
    background-color: rgb(224, 224, 224);
    border: none;
    border-radius: 8px;
    margin-top: 20px;
    padding: 8px 10px;
    margin-left:60px;
   }

   input.btn:hover {
    cursor: pointer;
  }

  



</style>
{% endblock stylesheet %}
{% block content %}
<div class='container'>
    <div class='row'>
        <div class='col-md-12'>
            <h1 style="margin-top: 80px; margin-left: 60px; margin-bottom: 40px; font-size:30px;">Create Profile</h1>
            <form action="" method="POST" class="form-horizontal" enctype="multipart/form-data">    
                {% csrf_token %}
                {% for field in form.visible_fields %}
                    <div class="form-group {{ field.name }}">
                        {{ field.label_tag }}
                        <div class='col-sm-10'>
                            {{ field }}
                            {% if field.help_text %}
                                <p class="help-block">{{ field.help_text }}</p>
                            {% endif %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    {{ error }}
                                </div>
                            {% endfor %}

                              
                        </div>
                    </div>
                {% endfor %}
                <input type="submit" class="btn " />
            </form>
        </div>
    </div>
</div>

{% endblock content%}

phoing/myApp/templates/myApp/profile/profile_delete.html
{% extends 'myApp/layout.html' %}

{% load static %}
{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/profile_delete.css' %}">

<style>
    *{
        font-family: "NanumSquare", sans-serif;
    }
</style>

{% endblock stylesheet %}

{% block content %}
<div class="container">
    <div class="profile_delete">
        <h1>User delete</h1><br>
        <p>정말로 탈퇴하시겠습니까?</p>
        <form action="{% url 'myApp:profile_delete' user.pk %}" method="POST">
            {% csrf_token %}
            <input class="delete_btn" type="submit" value="탈퇴"/>
        </form>
    </div>
</div>
{% endblock content%}

phoing/myApp/templates/myApp/profile/profile_detail.html
{% extends 'myApp/layout.html' %}

{% load static %}
{% block stylesheet %}
<link href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/moonspam/NanumSquare@1.0/nanumsquare.css">

<style>
    * {
        margin: 0;
        padding: 0;
        text-decoration: none;
        list-style-type: none;
        font-family: "NanumSquare", sans-serif;
    }

    /*category btn*/

    * {
        box-sizing: border-box;
        scroll-behavior: smooth;
        color: black;

    }


    /* Dropdown Button */
    .dropbtn {
        display: flex;
        margin: auto 1px;
        padding: 5px;
        justify-content: center;
    }

    /* The container <div> - needed to position the dropdown content */
    .dropdown {
        position: relative;
        display: inline-block;
    }

    /* Dropdown Content (Hidden by Default) */
    .dropdown-content {
        display: none;
        position: absolute;
        min-width: 160px;
        z-index: 1;
        margin-left: 2px;
    }

    /* Links inside the dropdown */
    .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
        background-color: white;
        border: #ddd solid 1px;
    }

    /* Change color of dropdown links on hover */
    .dropdown-content a:hover {
        background-color: #ddd;
    }

    /* Show the dropdown menu on hover */
    .dropdown:hover .dropdown-content {
        display: block;
    }


    /**/
    * {
        box-sizing: border-box;
    }


    .btn {
        width: 150px;
        height: 50px;
        border: 1px solid #333;
        font-family: "Cinzel", serif;
        font-size: 15px;
        cursor: pointer;
        -webkit-tap-highlight-color: transparent;
        display: flex;
        align-items: center;
        justify-content: center;
        position: relative;
        z-index: 0;
        transition: 1s;
    }

    .btn::before,
    .btn::after {
        position: absolute;
        background: #fff;
        z-index: -1;
        transition: 1s;
        content: "";
    }

    .btn::before {
        height: 50px;
        width: 130px;
    }

    .btn::after {
        width: 150px;
        height: 30px;
    }

    .noselect {
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    .btn:hover::before {
        width: 0px;
        background: #fff;
    }

    .btn:hover::after {
        height: 0px;
        background: #fff;
    }

    .btn:hover {
        background: #fff;
    }


    .choose a,
    .profile_button a {
        color: black;
    }

    .container {
     margin: 3% 4%;
    }

    .choose {
        display: flex;
        margin: auto 1px;
        padding: 2px;
        margin-top: 3%;
        justify-content: center;
        align-items: center;
    }

    .choose_profile {
        padding: 5px;
        margin-right: 2%;
    }

    .choose_profile span {
        font-weight:900;
    }

    .dropdown{
        margin-right: 2%;
    }

   

    /**/

    .profile_container {
        display: grid;
        grid-template-columns: 200px 1fr;
        padding-left: 1px;
        margin-top: 8%;
    }

    .profile_image {
        width: 150px;
        height: 150px;
        border-radius: 100px;
    }

    .profile_username,
    .profile_email,
    .profile_category,
    .profile_desc {
        display: grid;
        grid-template-columns: 110px 1fr;
        margin-right: 20px;
        padding: 10px;
    }

    .profile_info {
        margin-right: 5%;
        color: #878787;
    }

    .profile_saved {
        margin-top: 50px;
    }

    .profile_button {
        display: flex;
        justify-content: flex-end;
        margin: auto 1px;
        padding: 2px;
    }

    .edit_btn {
        border: 1px solid black;
        padding: 5px;
        margin: 5px;
    }

    .delete_btn {
        border: 1px solid black;
        padding: 5px;
        margin: 5px;
    }
</style>
{% endblock stylesheet %}

{% block content %}


<div class="container">
    <div class="choose">
        {% if request.user.pk == user.pk %}
        <a class="choose_profile" href="{% url 'myApp:profile_detail' user.pk %}">
            <div class="btn"><span class="noselect">My Profile</span></div>
        </a>
        <div class="dropdown">
            <div class="dropbtn">
                <div class="btn"><span class="noselect">My Posts</span></div>
            </div>
            <div class="dropdown-content">
                <a href="javascript:void(0)" onclick="onClickLink('contact')">Contact</a>
                <a href="javascript:void(0)" onclick="onClickLink('portfolio')">Portfolio</a>
            </div>
        </div>
        <div class="dropdown">
            <div class="dropbtn">
                <div class="btn"><span class="noselect">My Saves</span></div>
            </div>
            <div class="dropdown-content">
                <a href="{% url 'myApp:profile_detail_saves' user.pk %}" onclick="onClickLink('contact')">Contact</a>
                <a href="{% url 'myApp:profile_detail_saves' user.pk %}" onclick="onClickLink('portfolio')">Portfolio</a>
            </div>
        </div>
        {% else %}
        <a class="choose_profile" href="{% url 'myApp:profile_detail' user.pk %}"><div class="btn"><span class="noselect">Profile</span></div></a>
        <div class="dropdown">
            <div class="dropbtn">
                <div class="btn"><span class="noselect"><a href="{% url 'myApp:profile_detail_posts' user.pk %}"
                            onclick="onClickLink('all')">Posts</a></span></div>
            </div>
            <div class="dropdown-content">
                <a href="javascript:void(0)" onclick="onClickLink('contact')">Contact</a>
                <a href="javascript:void(0)" onclick="onClickLink('portfolio')">Portfolio</a>            
            </div>
        </div>
        {% endif %}
    </div>


    <div class="profile_container">
        <div>

            {% if user.image  %}
            <img class="profile_image" src="{{user.image.url}}" alt="profile_image" width="20%">
            {% else %}
            <img class="profile_image"
                src="https://cdn.iconscout.com/icon/free/png-512/account-profile-avatar-man-circle-round-user-30452.png"
                alt="profile_image" width="20%">
            {% endif %}


        </div>

        
        <div class="profile_info_container">
            <ul>
                <li>
                    <div class="profile_username">
                        <div class="profile_info">username</div>
                        <div class="profile_info_username">{{user.username}}</div>
                    </div>
                </li>
                <li>
                    <div class="profile_email">
                        <div class="profile_info">email</div>
                        {% if not user.email %}
                        <!-- <div class="profile_info_email">이메일 정보가 없습니다.</div> -->
                        {% else %}
                        <div class="profile_info_email">{{user.email}}</div>
                        {% endif %}
                    </div>
                </li>
                <li>
                    <div class="profile_category">
                        <div class="profile_info">category</div>
                        <div class="profile_info_category">{{user.category}}</div>
                    </div>
                </li>
                <li>
                    <div class="profile_desc">
                        <div class="profile_info">프로필 소개</div>
                        <div class="profile_info_desc">{{user.desc}}</div>
                    </div>
                </li>
            </ul>
        </div>
    </div>

    {% if request_user.username == user.username %}
    <div class="profile_button">
        <a class="edit_btn" href="{% url 'myApp:profile_update' user.pk %}">프로필 수정</a>
        <a class="edit_btn" href="{% url 'myApp:profile_update_password' user.pk %}">비밀번호 변경</a>
        <a class="delete_btn" href="{% url 'myApp:profile_delete' user.pk %}">탈퇴</a>
    </div>
    {% endif %}

</div>
</div>

<!--filter form-->
<div style="height: 0;">
    <form id="searchForm" method="get" action="{% url 'myApp:profile_detail_posts' user.pk %}">
        <!--category-->
        <input type="hidden" id="category" name="category" value="{{ category }}">

    </form>
</div>
{% endblock content%}




{% block script %}
<script>
    //category
    const onClickLink = (category) => {
        const categoryIdInput = document.querySelector('#category')
        categoryIdInput.value = category
        const searchForm = document.querySelector('#searchForm')
        searchForm.submit()
    }
</script>
{% endblock script %}